language: node_js
node_js:
  - '12'
  - '10'

cache: yarn

matrix:
  include:
    - node_js:
        - '12'
        - '10'
      addons:
        chrome: stable
    - node_js:
        - '12'
        - '10'
